# docker-compose.override.yml
# Настройки для локальной разработки.
# Этот файл автоматически подхватывается Docker Compose и расширяет/переопределяет
# настройки из базового docker-compose.yml.

version: '3.8'

# Определяем якорь для пользователя, который будет запускать сервис.
# Это решает проблему с правами доступа к файлам, созданным в контейнере.
x-backend-user: &backend-user "${UID:-1000}:${GID:-1000}"

services:
  backend:
    user: *backend-user
    volumes:
      # Синхронизируем текущую директорию с рабочей директорией в контейнере
      # для мгновенного отражения изменений в коде.
      - .:/app