version: '3.8'

x-backend-user: &backend-user "${UID:-1000}:${GID:-1000}"

services:
  backend:
    user: *backend-user
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    # Для разработки можно временно отключить healthcheck,
    # чтобы избежать проблем при первом запуске или во время отладки.
    healthcheck:
      disable: true