-- Таблица для типов активов
CREATE TABLE "AssetType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(500),
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для статусов устройств
CREATE TABLE "DeviceStatus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(500),
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для отделов
CREATE TABLE "Department" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(500),
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для местоположений
CREATE TABLE "Location" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(500),
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для производителей
CREATE TABLE "Manufacturer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(500),
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для сотрудников
CREATE TABLE "Employee" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(255) NOT NULL,
  "last_name" varchar(255) NOT NULL,
  "patronymic" varchar(255),
  "employee_id" varchar(255) UNIQUE,
  "email" varchar(255) UNIQUE,
  "phone_number" varchar(255), -- ИСПРАВЛЕНО: переименовано с "phone" на "phone_number"
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для моделей устройств
CREATE TABLE "DeviceModel" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "manufacturer_id" int NOT NULL,
  "asset_type_id" int NOT NULL,
  "description" varchar(500),
  "specification" jsonb,
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для самих устройств
CREATE TABLE "Device" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_number" varchar(255) UNIQUE NOT NULL,
  "serial_number" varchar(255),
  "mac_address" varchar(255),
  "ip_address" varchar(255),
  "notes" text,
  "source" varchar(50) NOT NULL,
  "purchase_date" date,
  "warranty_end_date" date,
  "price" decimal(10,2),
  "expected_lifespan_years" int,
  "current_wear_percentage" decimal(5,2),
  "added_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "attributes" jsonb,
  "device_model_id" int NOT NULL,
  "asset_type_id" int NOT NULL,
  "status_id" int NOT NULL,
  "department_id" int,
  "location_id" int,
  "employee_id" int
);

-- Таблица для вложений/файлов, связанных с устройствами
CREATE TABLE "Attachment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" int NOT NULL,
  "filename" varchar(255) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "file_type" varchar(100),
  "uploaded_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()), -- Добавлено
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Таблица для логов действий (например, кто, что, когда изменил)
CREATE TABLE "ActionLog" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "user_id" int,
  "action_type" varchar(50) NOT NULL,
  "entity_type" varchar(50) NOT NULL,
  "entity_id" int NOT NULL,
  "details" jsonb,
  "created_at" timestamp DEFAULT (now()), -- Добавлено (хотя timestamp уже есть, можно оставить для единообразия)
  "updated_at" timestamp DEFAULT (now())  -- Добавлено
);

-- Определение внешних ключей

ALTER TABLE "DeviceModel" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "Manufacturer" ("id");

ALTER TABLE "DeviceModel" ADD FOREIGN KEY ("asset_type_id") REFERENCES "AssetType" ("id");

ALTER TABLE "Device" ADD FOREIGN KEY ("device_model_id") REFERENCES "DeviceModel" ("id");

ALTER TABLE "Device" ADD FOREIGN KEY ("asset_type_id") REFERENCES "AssetType" ("id");

ALTER TABLE "Device" ADD FOREIGN KEY ("status_id") REFERENCES "DeviceStatus" ("id");

ALTER TABLE "Device" ADD FOREIGN KEY ("department_id") REFERENCES "Department" ("id");

ALTER TABLE "Device" ADD FOREIGN KEY ("location_id") REFERENCES "Location" ("id");

ALTER TABLE "Device" ADD FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id");

ALTER TABLE "Attachment" ADD FOREIGN KEY ("device_id") REFERENCES "Device" ("id");