"""Add foreign key from DeviceModel to AssetType

Revision ID: e4500be6f749
Revises: bc78fd1429a7
Create Date: 2025-09-18 17:54:07.185817

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4500be6f749"
down_revision: str | None = "bc78fd1429a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devicemodels", sa.Column("description", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "devicemodels", sa.Column("asset_type_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "devicemodels", "assettypes", ["asset_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "devicemodels", type_="foreignkey")
    op.drop_column("devicemodels", "asset_type_id")
    op.drop_column("devicemodels", "description")
    # ### end Alembic commands ###
