"""Add unique constraint to locations

Revision ID: 9abbc70e6178
Revises: f405d01a666c
Create Date: 2025-09-23 16:00:38.338912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abbc70e6178'
down_revision: Union[str, None] = 'f405d01a666c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_name_key', 'locations', type_='unique')
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_unique_constraint('uq_locations_name', 'locations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_locations_name', 'locations', type_='unique')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.create_unique_constraint('locations_name_key', 'locations', ['name'])
    # ### end Alembic commands ###
