"""add_slugs_and_legacy_number

Revision ID: 10160bb2b153
Revises: d84a943950b0
Create Date: 2025-12-07 13:55:41.319019

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10160bb2b153'
down_revision: str | None = 'd84a943950b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable=True first
    op.add_column('assettypes', sa.Column('slug', sa.String(length=50), nullable=True, comment='Системный идентификатор (неизменяемый)'))
    op.add_column('departments', sa.Column('slug', sa.String(length=50), nullable=True, comment='Системный идентификатор (неизменяемый)'))
    op.add_column('devicestatuses', sa.Column('slug', sa.String(length=50), nullable=True, comment='Системный идентификатор (неизменяемый)'))
    op.add_column('locations', sa.Column('slug', sa.String(length=50), nullable=True, comment='Системный идентификатор (неизменяемый)'))

    op.add_column('devices', sa.Column('legacy_inventory_number', sa.String(length=100), nullable=True, comment='Инвентарный номер из старой системы учета'))
    op.create_index(op.f('ix_devices_legacy_inventory_number'), 'devices', ['legacy_inventory_number'], unique=False)

    # 2. Data Migration: Generate slugs for existing rows
    # (Примитивная транслитерация или просто копирование имени для старых данных)
    op.execute("UPDATE assettypes SET slug = lower(replace(name, ' ', '_')) WHERE slug IS NULL")
    op.execute("UPDATE devicestatuses SET slug = lower(replace(name, ' ', '_')) WHERE slug IS NULL")
    op.execute("UPDATE departments SET slug = lower(replace(name, ' ', '_')) WHERE slug IS NULL")
    op.execute("UPDATE locations SET slug = lower(replace(name, ' ', '_')) WHERE slug IS NULL")

    # 3. Alter columns to nullable=False and create indexes
    op.alter_column('assettypes', 'slug', nullable=False, existing_type=sa.String(length=50), existing_comment='Системный идентификатор (неизменяемый)')
    op.create_index(op.f('ix_assettypes_slug'), 'assettypes', ['slug'], unique=True)

    op.alter_column('departments', 'slug', nullable=False, existing_type=sa.String(length=50), existing_comment='Системный идентификатор (неизменяемый)')
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=True)

    op.alter_column('devicestatuses', 'slug', nullable=False, existing_type=sa.String(length=50), existing_comment='Системный идентификатор (неизменяемый)')
    op.create_index(op.f('ix_devicestatuses_slug'), 'devicestatuses', ['slug'], unique=True)

    op.alter_column('locations', 'slug', nullable=False, existing_type=sa.String(length=50), existing_comment='Системный идентификатор (неизменяемый)')
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.drop_column('locations', 'slug')
    op.drop_index(op.f('ix_devicestatuses_slug'), table_name='devicestatuses')
    op.drop_column('devicestatuses', 'slug')
    op.drop_index(op.f('ix_devices_legacy_inventory_number'), table_name='devices')
    op.drop_column('devices', 'legacy_inventory_number')
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_column('departments', 'slug')
    op.drop_index(op.f('ix_assettypes_slug'), table_name='assettypes')
    op.drop_column('assettypes', 'slug')
    # ### end Alembic commands ###
