"""add category field to tags

Revision ID: 7a9c8d6b5e4f
Revises: 413e5e7e7c66
Create Date: 2025-10-12 18:03:14.542349

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a9c8d6b5e4f"
down_revision: str | None = "413e5e7e7c66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("category", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "category")
    # ### end Alembic commands ###
