"""Add description and relationship to Department model

Revision ID: 34859191a603
Revises: 09e830d715e0
Create Date: 2025-09-18 18:03:15.127723

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34859191a603'
down_revision: str | None = '09e830d715e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'description')
    # ### end Alembic commands ###
