"""Add user foreign key to ActionLog

Revision ID: 1ef7d746b480
Revises: acc02a2bf57b
Create Date: 2025-11-29 07:27:41.637112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef7d746b480'
down_revision: Union[str, None] = 'acc02a2bf57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'actionlog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actionlog', type_='foreignkey')
    # ### end Alembic commands ###
