"""добавим description to tags

Revision ID: 8fc178ad1a1b
Revises: 7a9c8d6b5e4f
Create Date: 2025-10-19 14:07:31.320611

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fc178ad1a1b"
down_revision: str | None = "7a9c8d6b5e4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "description")
    # ### end Alembic commands ###
