"""Add relationship between DeviceModel and AssetType

Revision ID: 09e830d715e0
Revises: e4500be6f749
Create Date: 2025-09-18 17:59:20.179290

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '09e830d715e0'
down_revision: str | None = 'e4500be6f749'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
