"""Initial migration from scratch

Revision ID: f435cc528891
Revises: 
Create Date: 2025-07-13 08:20:49.873483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f435cc528891'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActionLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ActionLog_id'), 'ActionLog', ['id'], unique=False)
    op.create_table('AssetType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AssetType_id'), 'AssetType', ['id'], unique=False)
    op.create_index(op.f('ix_AssetType_name'), 'AssetType', ['name'], unique=True)
    op.create_table('Department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Department_id'), 'Department', ['id'], unique=False)
    op.create_index(op.f('ix_Department_name'), 'Department', ['name'], unique=True)
    op.create_table('DeviceStatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DeviceStatus_id'), 'DeviceStatus', ['id'], unique=False)
    op.create_index(op.f('ix_DeviceStatus_name'), 'DeviceStatus', ['name'], unique=True)
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_Employee_email'), 'Employee', ['email'], unique=True)
    op.create_index(op.f('ix_Employee_id'), 'Employee', ['id'], unique=False)
    op.create_table('Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Location_id'), 'Location', ['id'], unique=False)
    op.create_index(op.f('ix_Location_name'), 'Location', ['name'], unique=True)
    op.create_table('Manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Manufacturer_id'), 'Manufacturer', ['id'], unique=False)
    op.create_index(op.f('ix_Manufacturer_name'), 'Manufacturer', ['name'], unique=True)
    op.create_table('DeviceModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('specification', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['AssetType.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['Manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DeviceModel_id'), 'DeviceModel', ['id'], unique=False)
    op.create_index(op.f('ix_DeviceModel_name'), 'DeviceModel', ['name'], unique=True)
    op.create_table('Device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_lifespan_years', sa.Integer(), nullable=True),
    sa.Column('current_wear_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('device_model_id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['AssetType.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ),
    sa.ForeignKeyConstraint(['device_model_id'], ['DeviceModel.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['Location.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['DeviceStatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_number')
    )
    op.create_index(op.f('ix_Device_id'), 'Device', ['id'], unique=False)
    op.create_table('Attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['Device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Attachment_id'), 'Attachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Attachment_id'), table_name='Attachment')
    op.drop_table('Attachment')
    op.drop_index(op.f('ix_Device_id'), table_name='Device')
    op.drop_table('Device')
    op.drop_index(op.f('ix_DeviceModel_name'), table_name='DeviceModel')
    op.drop_index(op.f('ix_DeviceModel_id'), table_name='DeviceModel')
    op.drop_table('DeviceModel')
    op.drop_index(op.f('ix_Manufacturer_name'), table_name='Manufacturer')
    op.drop_index(op.f('ix_Manufacturer_id'), table_name='Manufacturer')
    op.drop_table('Manufacturer')
    op.drop_index(op.f('ix_Location_name'), table_name='Location')
    op.drop_index(op.f('ix_Location_id'), table_name='Location')
    op.drop_table('Location')
    op.drop_index(op.f('ix_Employee_id'), table_name='Employee')
    op.drop_index(op.f('ix_Employee_email'), table_name='Employee')
    op.drop_table('Employee')
    op.drop_index(op.f('ix_DeviceStatus_name'), table_name='DeviceStatus')
    op.drop_index(op.f('ix_DeviceStatus_id'), table_name='DeviceStatus')
    op.drop_table('DeviceStatus')
    op.drop_index(op.f('ix_Department_name'), table_name='Department')
    op.drop_index(op.f('ix_Department_id'), table_name='Department')
    op.drop_table('Department')
    op.drop_index(op.f('ix_AssetType_name'), table_name='AssetType')
    op.drop_index(op.f('ix_AssetType_id'), table_name='AssetType')
    op.drop_table('AssetType')
    op.drop_index(op.f('ix_ActionLog_id'), table_name='ActionLog')
    op.drop_table('ActionLog')
    # ### end Alembic commands ###
