"""Add user foreign key to ActionLog

Revision ID: 1ef7d746b480
Revises: acc02a2bf57b
Create Date: 2025-11-29 07:27:41.637112

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ef7d746b480'
down_revision: str | None = 'acc02a2bf57b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'actionlog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actionlog', type_='foreignkey')
    # ### end Alembic commands ###
