"""Add description to AssetType

Revision ID: bc78fd1429a7
Revises: c64ca42f0f7a
Create Date: 2025-09-18 17:50:29.543637

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc78fd1429a7'
down_revision: str | None = 'c64ca42f0f7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assettypes', sa.Column('description', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assettypes', 'description')
    # ### end Alembic commands ###
