"""Add supplier relationship to Device model

Revision ID: 88b1196ca226
Revises: f54c7505ea53
Create Date: 2025-09-26 07:46:01.331517

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88b1196ca226'
down_revision: str | None = 'f54c7505ea53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'supplier_id')
    # ### end Alembic commands ###
