"""Add description to AssetType

Revision ID: bc78fd1429a7
Revises: c64ca42f0f7a
Create Date: 2025-09-18 17:50:29.543637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc78fd1429a7'
down_revision: Union[str, None] = 'c64ca42f0f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assettypes', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assettypes', 'description')
    # ### end Alembic commands ###
