"""Add description to AssetType

Revision ID: c64ca42f0f7a
Revises: 6eaecc82f376
Create Date: 2025-09-18 17:48:16.818442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64ca42f0f7a'
down_revision: Union[str, None] = '6eaecc82f376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
