"""add_hardware_components

Revision ID: 369432567127
Revises: 1ef7d746b480
Create Date: 2025-12-03 11:31:16.800106

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '369432567127'
down_revision: str | None = '1ef7d746b480'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('component_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_history_asset_id'), 'component_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_component_history_id'), 'component_history', ['id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_asset_id'), 'components', ['asset_id'], unique=False)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_serial_number'), 'components', ['serial_number'], unique=False)
    op.create_table('components_cpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('base_clock_mhz', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components_gpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components_ram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_mb', sa.Integer(), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_label', sa.String(length=50), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('components_storage')
    op.drop_table('components_ram')
    op.drop_table('components_gpu')
    op.drop_table('components_cpu')
    op.drop_index(op.f('ix_components_serial_number'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_index(op.f('ix_components_asset_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_component_history_id'), table_name='component_history')
    op.drop_index(op.f('ix_component_history_asset_id'), table_name='component_history')
    op.drop_table('component_history')
    # ### end Alembic commands ###
