"""Update Employee model with detailed fields

Revision ID: 6eaecc82f376
Revises: 01a80f183d11
Create Date: 2025-09-18 16:36:10.033018

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6eaecc82f376"
down_revision: str | None = "01a80f183d11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        comment="Фамилия",
        existing_nullable=False,
    )
    op.alter_column(
        "employees",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        comment="Имя",
        existing_nullable=False,
    )
    op.alter_column(
        "employees",
        "patronymic",
        existing_type=sa.VARCHAR(length=50),
        comment="Отчество",
        existing_nullable=True,
    )
    op.alter_column(
        "employees",
        "employee_id",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        comment="Табельный номер",
    )
    op.alter_column(
        "employees",
        "position",
        existing_type=sa.VARCHAR(length=255),
        comment="Должность",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "position",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Должность",
        existing_nullable=True,
    )
    op.alter_column(
        "employees",
        "employee_id",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        comment=None,
        existing_comment="Табельный номер",
    )
    op.alter_column(
        "employees",
        "patronymic",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Отчество",
        existing_nullable=True,
    )
    op.alter_column(
        "employees",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Имя",
        existing_nullable=False,
    )
    op.alter_column(
        "employees",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Фамилия",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
