"""Add unique constraint to device models

Revision ID: f405d01a666c
Revises: f621c06f6b7b
Create Date: 2025-09-23 14:54:18.072450

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f405d01a666c"
down_revision: str | None = "f621c06f6b7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_devicemodel_name_manufacturer", "devicemodels", ["name", "manufacturer_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_devicemodel_name_manufacturer", "devicemodels", type_="unique"
    )
    # ### end Alembic commands ###
