"""Add unique constraint to device_statuses

Revision ID: 09b093ccb03c
Revises: 9abbc70e6178
Create Date: 2025-09-23 17:20:22.799111

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09b093ccb03c'
down_revision: str | None = '9abbc70e6178'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('devicestatuses_name_key', 'devicestatuses', type_='unique')
    op.create_index(op.f('ix_devicestatuses_name'), 'devicestatuses', ['name'], unique=True)
    op.create_unique_constraint('uq_devicestatuses_name', 'devicestatuses', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_devicestatuses_name', 'devicestatuses', type_='unique')
    op.drop_index(op.f('ix_devicestatuses_name'), table_name='devicestatuses')
    op.create_unique_constraint('devicestatuses_name_key', 'devicestatuses', ['name'])
    # ### end Alembic commands ###
