"""Create DepartmentService and add unique constraint

Revision ID: 35b42474934b
Revises: ef2aae8cb837
Create Date: 2025-09-23 17:30:25.754679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b42474934b'
down_revision: Union[str, None] = 'ef2aae8cb837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_name_key', 'departments', type_='unique')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_unique_constraint('uq_departments_name', 'departments', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_departments_name', 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_unique_constraint('departments_name_key', 'departments', ['name'])
    # ### end Alembic commands ###
