"""make_employee_id_optional

Revision ID: 2639f2c11d34
Revises: d1fc03a6856f
Create Date: 2025-11-23 16:36:00.038698

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2639f2c11d34"
down_revision: str | None = "d1fc03a6856f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "employee_id",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="Табельный номер",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "employee_id",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="Табельный номер",
    )
    # ### end Alembic commands ###
