"""add default value for source field

Revision ID: acc02a2bf57b
Revises: 2b767344c239
Create Date: 2025-11-23 17:38:44.319079

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'acc02a2bf57b'
down_revision: str | None = '2b767344c239'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
