"""Add created_at and updated_at columns from BaseMixin

Revision ID: 7f5b4c34c002
Revises: 63acff837841
Create Date: 2025-06-15 21:38:44.696608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f5b4c34c002'
down_revision: Union[str, None] = '63acff837841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### Удалена некорректная операция для ActionLog.id ###
    pass
    op.alter_column('ActionLog', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ActionLog', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ActionLog', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ActionLog_id'), 'ActionLog', ['id'], unique=False)
    # ### Удалена некорректная операция для AssetType.id ###
    pass
    op.alter_column('AssetType', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('AssetType', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('AssetType_name_key', 'AssetType', type_='unique')
    op.create_index(op.f('ix_AssetType_id'), 'AssetType', ['id'], unique=False)
    op.create_index(op.f('ix_AssetType_name'), 'AssetType', ['name'], unique=True)
    # ### Удалена некорректная операция для Attachment.id ###
    pass
    op.alter_column('Attachment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('Attachment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_Attachment_id'), 'Attachment', ['id'], unique=False)
    # ### Удалена некорректная операция для Department.id ###
    pass
    op.alter_column('Department', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('Department', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('Department_name_key', 'Department', type_='unique')
    op.create_index(op.f('ix_Department_id'), 'Department', ['id'], unique=False)
    op.create_index(op.f('ix_Department_name'), 'Department', ['name'], unique=True)
    op.add_column('Device', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### Удалена некорректная операция для Device.id ###
    pass
    op.alter_column('Device', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('Device', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_Device_id'), 'Device', ['id'], unique=False)
    op.drop_column('Device', 'added_at')
    # ### Удалена некорректная операция для DeviceModel.id ###
    pass
    op.alter_column('DeviceModel', 'specification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('DeviceModel', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('DeviceModel', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_DeviceModel_id'), 'DeviceModel', ['id'], unique=False)
    op.create_index(op.f('ix_DeviceModel_name'), 'DeviceModel', ['name'], unique=True)
    # ### Удалена некорректная операция для DeviceStatus.id ###
    pass
    op.alter_column('DeviceStatus', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('DeviceStatus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('DeviceStatus_name_key', 'DeviceStatus', type_='unique')
    op.create_index(op.f('ix_DeviceStatus_id'), 'DeviceStatus', ['id'], unique=False)
    op.create_index(op.f('ix_DeviceStatus_name'), 'DeviceStatus', ['name'], unique=True)
    # ### Удалена некорректная операция для Employee.id ###
    pass
    op.alter_column('Employee', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('Employee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('Employee_email_key', 'Employee', type_='unique')
    op.create_index(op.f('ix_Employee_email'), 'Employee', ['email'], unique=True)
    op.create_index(op.f('ix_Employee_id'), 'Employee', ['id'], unique=False)
    # ### Удалена некорректная операция для Location.id ###
    pass
    op.alter_column('Location', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('Location', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('Location_name_key', 'Location', type_='unique')
    op.create_index(op.f('ix_Location_id'), 'Location', ['id'], unique=False)
    op.create_index(op.f('ix_Location_name'), 'Location', ['name'], unique=True)
    # ### Удалена некорректная операция для Manufacturer.id ###
    pass
    op.alter_column('Manufacturer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('Manufacturer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('Manufacturer_name_key', 'Manufacturer', type_='unique')
    op.create_index(op.f('ix_Manufacturer_id'), 'Manufacturer', ['id'], unique=False)
    op.create_index(op.f('ix_Manufacturer_name'), 'Manufacturer', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Manufacturer_name'), table_name='Manufacturer')
    op.drop_index(op.f('ix_Manufacturer_id'), table_name='Manufacturer')
    op.create_unique_constraint('Manufacturer_name_key', 'Manufacturer', ['name'])
    op.alter_column('Manufacturer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Manufacturer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для Manufacturer.id из downgrade ###
    pass
    op.drop_index(op.f('ix_Location_name'), table_name='Location')
    op.drop_index(op.f('ix_Location_id'), table_name='Location')
    op.create_unique_constraint('Location_name_key', 'Location', ['name'])
    op.alter_column('Location', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Location', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для Location.id из downgrade ###
    pass
    op.drop_index(op.f('ix_Employee_id'), table_name='Employee')
    op.drop_index(op.f('ix_Employee_email'), table_name='Employee')
    op.create_unique_constraint('Employee_email_key', 'Employee', ['email'])
    op.alter_column('Employee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Employee', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для Employee.id из downgrade ###
    pass
    op.drop_index(op.f('ix_DeviceStatus_name'), table_name='DeviceStatus')
    op.drop_index(op.f('ix_DeviceStatus_id'), table_name='DeviceStatus')
    op.create_unique_constraint('DeviceStatus_name_key', 'DeviceStatus', ['name'])
    op.alter_column('DeviceStatus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('DeviceStatus', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для DeviceStatus.id из downgrade ###
    pass
    op.drop_index(op.f('ix_DeviceModel_name'), table_name='DeviceModel')
    op.drop_index(op.f('ix_DeviceModel_id'), table_name='DeviceModel')
    op.alter_column('DeviceModel', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('DeviceModel', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('DeviceModel', 'specification',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### Удалена некорректная операция для DeviceModel.id из downgrade ###
    pass
    op.add_column('Device', sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Device_id'), table_name='Device')
    op.alter_column('Device', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Device', 'attributes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### Удалена некорректная операция для Device.id из downgrade ###
    pass
    op.drop_column('Device', 'created_at')
    op.drop_index(op.f('ix_Department_name'), table_name='Department')
    op.drop_index(op.f('ix_Department_id'), table_name='Department')
    op.create_unique_constraint('Department_name_key', 'Department', ['name'])
    op.alter_column('Department', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Department', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для Department.id из downgrade ###
    pass
    op.drop_index(op.f('ix_Attachment_id'), table_name='Attachment')
    op.alter_column('Attachment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Attachment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для Attachment.id из downgrade ###
    pass
    op.drop_index(op.f('ix_AssetType_name'), table_name='AssetType')
    op.drop_index(op.f('ix_AssetType_id'), table_name='AssetType')
    op.create_unique_constraint('AssetType_name_key', 'AssetType', ['name'])
    op.alter_column('AssetType', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('AssetType', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### Удалена некорректная операция для AssetType.id из downgrade ###
    pass
    op.drop_index(op.f('ix_ActionLog_id'), table_name='ActionLog')
    op.alter_column('ActionLog', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ActionLog', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ActionLog', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### Удалена некорректная операция для ActionLog.id из downgrade ###
    pass
    # ### end Alembic commands ###
