"""add_supplier_columns

Revision ID: 2b767344c239
Revises: 2639f2c11d34
Create Date: 2025-11-23 17:12:51.170397

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b767344c239'
down_revision: str | None = '2639f2c11d34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'suppliers', sa.Column('contact_person', sa.String(length=100), nullable=True)
    )
    op.add_column('suppliers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column(
        'suppliers', sa.Column('address', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'address')
    op.drop_column('suppliers', 'email')
    op.drop_column('suppliers', 'phone')
    op.drop_column('suppliers', 'contact_person')
    # ### end Alembic commands ###
