"""Update Employee model with detailed fields

Revision ID: 01a80f183d11
Revises: f029a47844f1
Create Date: 2025-09-18 16:30:56.221954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a80f183d11'
down_revision: Union[str, None] = 'f029a47844f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('patronymic', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'phone_number')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'employee_id')
    op.drop_column('employees', 'patronymic')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###
