"""Add employees relationship to Department

Revision ID: ae316e4eff6d
Revises: 34859191a603
Create Date: 2025-09-18 18:05:01.238486

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ae316e4eff6d'
down_revision: str | None = '34859191a603'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
