"""Create ManufacturerService and add unique constraint

Revision ID: ef2aae8cb837
Revises: 09b093ccb03c
Create Date: 2025-09-23 17:26:54.383837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2aae8cb837'
down_revision: Union[str, None] = '09b093ccb03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_manufacturers_name', 'manufacturers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_manufacturers_name', 'manufacturers', type_='unique')
    # ### end Alembic commands ###
