"""Create ManufacturerService and add unique constraint

Revision ID: ef2aae8cb837
Revises: 09b093ccb03c
Create Date: 2025-09-23 17:26:54.383837

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef2aae8cb837'
down_revision: str | None = '09b093ccb03c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_manufacturers_name', 'manufacturers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_manufacturers_name', 'manufacturers', type_='unique')
    # ### end Alembic commands ###
